#!/usr/bin/env ruby
require 'yaml'
require 'json'
require 'thor'
require 'ohm'

$basepath = File.dirname(__FILE__) + "/"
$actorpath = $basepath.gsub(/lib/, "actors")

required_files = Array.new
required_files << $basepath + "mixins.rb"
required_files << $basepath + "util.rb"
required_files << $basepath + "config.rb"
required_files << $basepath + "logger.rb"
required_files += Dir[ $basepath + 'cli/*.rb']
required_files << $basepath + "cli.rb"
required_files << $basepath + "model/contact.rb"
required_files << $basepath + "model/sla.rb"
required_files << $basepath + "model/group.rb"
required_files << $basepath + "model/event.rb"
required_files << $basepath + "model/issue.rb"
required_files.each { |file| require file }

Notifu::CONFIG = Notifu::Config.new.get
Ohm.redis = Redic.new Notifu::CONFIG[:redis_data]

Notifu::CLI::Root.start(ARGV)